plugins {
    id("kop.kotlin-base")
    id("io.micronaut.application")
    id("com.google.devtools.ksp")
}

micronaut {
    runtime("none")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("kubeofpie.*")
    }
}

dependencies {
    // SLF4J backend for the CLI runtime. Version managed by the Micronaut BOM.
    // logback.xml lives in :core and reads the root level from ${KOP_LOG_LEVEL:-OFF}.
    "runtimeOnly"("ch.qos.logback:logback-classic")
}

configure<JavaApplication> {
    // sqlite-jdbc loads its native lib via System::load, which JDK 24+ flags as a restricted
    // operation unless the caller is explicitly granted native access. Applies to both
    // `run` and the start scripts generated by the application plugin.
    applicationDefaultJvmArgs = listOf("--enable-native-access=ALL-UNNAMED")
}